services:
  # Backend API Service
  - type: web
    name: projectcourse-backend
    runtime: node
    buildCommand: |
      cd backend
      npm ci --only=production=false
    startCommand: cd backend && npm start
    healthCheckPath: /health
    envVars:
      - key: NODE_ENV
        value: production
      - key: MONGO_URI
        sync: false  # Set this in Render dashboard
      - key: PORT
        value: 5000
    autoDeploy: true

  # Frontend Static Site
  - type: web
    name: projectcourse-frontend
    runtime: static
    buildCommand: |
      npm ci --only=production=false
      npm run build
    staticPublishPath: ./build
    envVars:
      - key: REACT_APP_API_URL
        fromService:
          type: web
          name: projectcourse-backend
          property: host
      - key: NODE_ENV
        value: production
    autoDeploy: true
    routes:
      - type: rewrite
        source: /*
        destination: /index.html

databases:
  # MongoDB Atlas connection (external)
  # No database service needed as we use MongoDB Atlas